# 0.5 addition to hours_between_backups is for safety purposes, so the script doesn't accidentally delete wrong files.

[main]
prefix = "+"

[LocalFS]
directory = "files" # please enter the full path, don't include the last backslash

[B2Blaze]
bucket = ""
folder = ""

[bucket_first]
#hours_between=
period_in_days= 7

[bucket_second]
hours_between= 4.5
period_in_days= 14

[bucket_third]
hours_between= 12.5
period_in_days= 28

[bucket_fourth]
hours_between= 24.5
period_in_days= 84

[bucket_fifth]
hours_between= 168.5
period_in_days= 84
