# 0.5 addition to hours_between_backups is for safety purposes, so the script doesn't accidentally delete wrong files.

[bucket.first]
#hours_between_backups=
period_in_days= 7

[bucket.second]
hours_between_backups= 4.5
period_in_days= 14

[bucket.third]
hours_between_backups= 12.5
period_in_days= 28

[bucket.fourth]
hours_between_backups= 24.5
period_in_days= 84

[bucket.fifth]
hours_between_backups= 168.5
period_in_days= 84
