[main]
# prefix used in the filename to separate the file/database name from the actual date string
prefix = "+"
# suffix used in the filename to separate the file/database name from the actual date string
suffix = "."
# datetime format the date string in the filename has
datetime_format = "%Y-%m-%d %H:%M:%S"
# alias for datetime_format
date_format = ""
# extra characters to be replaced by a blank string in filename strings
replace_extra = []

[LocalFS]
# please enter the absolute path to the directory
directory = ""

[B2Blaze]
# name of the bucket in B2
bucket = ""
# key_id obtained in the B2 Portal
key_id = ""
# an app_id is required to run this application, you can obtain one in the B2 Portal
app_key = ""
# environment, typically reffered to as realm by BackBlaze B2. can either be production, dev or staging.
realm = "production"


# FYI:
# - Don't define `hours_between` if you don't want any files in that bucket to be deleted.
# - `period_in_days` determines in which timeframe the bucket exists, so 7 is within a week from the first file Klean
#    comes across.
# - 0.5 addition to hours_between is for safety purposes, so the script doesn't accidentally delete wrong files.
#   It is recommended you do this if you decide to change or add any buckets.
[bucket_first]
#hours_between=
period_in_days= 7

[bucket_second]
hours_between= 4.5
period_in_days= 14

[bucket_third]
hours_between= 12.5
period_in_days= 28

[bucket_fourth]
hours_between= 24.5
period_in_days= 84

[bucket_fifth]
hours_between= 168.5
period_in_days= 84
